introduction: |-
        [Stackdriver Logging](https://cloud.google.com/logging/docs) allows you to store, search, analyze,
        monitor, and alert on log data and events from Google Cloud Platform and Amazon Web Services.
